# Generated by Django 3.1 on 2020-08-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('sequence', models.PositiveSmallIntegerField(default=1, verbose_name='Sequence')),
                ('createdDatatime', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('uri', models.CharField(max_length=100, verbose_name='URI')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('sequence', models.PositiveSmallIntegerField(default=1, verbose_name='Sequence')),
                ('createdDatatime', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('address', models.CharField(max_length=100, verbose_name='Addresse')),
                ('website', models.URLField(default='', verbose_name='Website')),
                ('scrap_api', models.URLField(default='', verbose_name='Scrap API')),
            ],
            options={
                'verbose_name': 'Chain',
                'verbose_name_plural': 'Chains',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('sequence', models.PositiveSmallIntegerField(default=1, verbose_name='Sequence')),
                ('createdDatatime', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('barcode', models.CharField(max_length=150, unique=True, verbose_name='Barcode')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('promotion', models.BooleanField(default=False, verbose_name='Promotion')),
                ('packaging', models.CharField(default='', max_length=30, verbose_name='Packaging')),
                ('url', models.URLField(default='', verbose_name='URL')),
                ('availability', models.CharField(choices=[('purchasable', 'Purchasable'), ('stopped', 'Stopped'), ('indispensable', 'Indispensable')], default='purchasable', max_length=15, verbose_name='Availability')),
                ('unitOfMeasure', models.CharField(default='', max_length=20, verbose_name='unitOfMeasure')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('sequence', models.PositiveSmallIntegerField(default=1, verbose_name='Sequence')),
                ('createdDatatime', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('address', models.CharField(max_length=100, verbose_name='Addresse')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.chain')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductStores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(verbose_name='Start date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.store')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(through='product.ProductStores', to='product.Store'),
        ),
    ]
