# Generated by Django 3.1 on 2020-08-06 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Sequence')),
                ('createdDatatime', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('address', models.CharField(max_length=100, verbose_name='Addresse')),
            ],
            options={
                'verbose_name': 'Chain',
                'verbose_name_plural': 'Chains',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Sequence')),
                ('createdDatatime', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('address', models.CharField(max_length=100, verbose_name='Addresse')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.chain')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Sequence')),
                ('createdDatatime', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('barcode', models.CharField(max_length=150, unique=True, verbose_name='Barcode')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.store')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'abstract': False,
            },
        ),
    ]
