# Generated by Django 3.1 on 2020-08-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(to='product.Store', verbose_name='Stores'),
        ),
    ]
